name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: MultiLine Commands
        run: |
          echo "First multiline"
          echo "Second multiline"
      - name: Print goodbye
        run: echo "Done - bye!"
        
